name: Test GitHub Pages Setup

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Pages Setup
        run: |
          echo "Testing GitHub Pages setup..."
          echo "Repository: ${{ github.repository }}"
          echo "Ref: ${{ github.ref }}"
          echo "SHA: ${{ github.sha }}"

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Create test artifact
        run: |
          mkdir -p test-dist
          echo "<h1>GitHub Pages Test</h1><p>If you can see this, GitHub Pages is working!</p>" > test-dist/index.html

      - name: Upload test artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './test-dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
